### ISSUE TITLE
"Being Testing" is not available on Cerner Code Console

### ISSUE THREAD

**Issue by jackychow** [cerner/smart-on-fhir-tutorial#103]
I am trying to test my app and need a test provider/patient credential. The guide for this repo stated the following 

`
Next log back into the code console and click on the app you’ve registered (My amazing SMART app). To launch your app through the code console click the “Begin Testing” button. The console will ask if the app you’re launching requires a patient in context. Our app requires a patient, so select yes and choose a patient. Please note the millennium username and password, you’ll need this credential when prompted. Finally, click launch and the console will redirect to your application.
`

However, I was unable to see a "Being Testing" button in my code console. Is this instruction still valid? If not, how should I go about getting a sandbox provider/patient credential for testing openid/Oauth2 for instance?

Thanks!

**Comment by shriniketsarkar** [comment]
Hello @jackychow an answer for your question was posted here : https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/cerner-fhir-developers/KGbgco1Yi_c/CAzpPKZyCwAJ 
Lets continue investigating this further on the Google Groups. 

Also any questions that you have regarding Cerner's SMART on FHIR framework ,[Cerner FHIR Developers Google Group](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/cerner-fhir-developers) is our official communication channel. You would get faster responses there as its monitored regularly by a team of Cerner developers.

**Comment by kpshek** [comment]
Closing this issue as the question was continued in our Google Group per @shriniketsarkar.
