### ISSUE TITLE
HL7

### ISSUE THREAD

**Issue by surhidamatya** [cerner/smart-on-fhir-tutorial#116]
Does smart app API provide HL7 values?

**Comment by kpshek** [comment]
Hi @surhidamatya - the SMART on FHIR specification does not outline any FHIR APIs that must be implemented. Rather, [SMART defines the mechanism by which an application is launched](http://www.hl7.org/fhir/smart-app-launch/).

You can read more about these specifications, including FHIR specifications around API profiles at https://docs.smarthealthit.org/. You can see what Cerner supports by going to https://fhir.cerner.com/.

You can engage with the broader FHIR & SMART communities via https://chat.fhir.org/.
