### ISSUE TITLE
FHIR commercial server 

### ISSUE THREAD

**Issue by Natarajan77** [cerner/smart-on-fhir-tutorial#131]
Do you know any FHIR commercial server available with exposed apis? On prem/cloud?

**Comment by MaxPhilips** [comment]
hi @Natarajan77 - here is an HL7-maintained list of FHIR reference servers you can check out: https://wiki.hl7.org/Publicly_Available_FHIR_Servers_for_testing

I can speak directly to Cerner's FHIR server which is documented here: http://fhir.cerner.com/

URLs for testing against Cerner's public sandbox are available here: http://fhir.cerner.com/millennium/r4/#service-root-url

Thanks,
Max (Cerner)
