### ISSUE TITLE
Failed to call FHIR Service after launch

### ISSUE THREAD

**Issue by aspencerpsu** [cerner/smart-on-fhir-tutorial#24]
Hi,

I forked the smarton-fhir tutorial onto my computer and I managed to follow the steps from [this url](http://engineering.cerner.com/smart-on-fhir-tutorial/#project-setup), including the outline for the project setup and registration without utilizing the bundle executable to deploy to github pages (just used git changes from the CL). I go to console code and click on the app I created and hit launch to transport me to the millenium sandbox login and enter the username and password provided. When I' redirected I get a p tag with the information:

> Failed to call FHIR Service

Is my patient call using your example suppose to take me to an error point?

-Akeem Spencer

**Comment by kolkheang** [comment]
@aspencerpsu - when you registered your application, you did not specify the scopes.  Please see this section http://engineering.cerner.com/smart-on-fhir-tutorial/#registration and select Patient scopes for Patient and Observation resources needed by the app to call FHIR.

FYI - We've a [developer Google Group](https://groups.google.com/forum/#!forum/cerner-fhir-developers) for question like this.

**Comment by aspencerpsu** [comment]
Okay perfect,

Forgot to check off the patient scopes required for the tutorial thank you.

I have another question but I'll post it on the google group.

Thank You
