### ISSUE TITLE
Git Page not loading

### ISSUE THREAD

**Issue by Genysys** [cerner/smart-on-fhir-tutorial#45]
Followed instructions here : http://engineering.cerner.com/smart-on-fhir-tutorial/#github-pages

But page still not loading when it switch branch to git page. Is there an open issue on this or am I doing something wrong?

**Comment by kolkheang** [comment]
By default GitHub Pages will not generate unless you make any change to the gh-pages branch.  Can you make an edit to the launch.html page in the gh-pages branch with your client id from code Console?

**Comment by kolkheang** [comment]
@Genysys  ^^

**Comment by kolkheang** [comment]
@Genysys  - if you update the branch above with the info from code Console, you'll be able to load the app.  Let us know if you run into any other issue.
