### ISSUE TITLE
Not able to run app against SMART Health IT Sandbox

### ISSUE THREAD

**Issue by cheriannet** [cerner/smart-on-fhir-tutorial#48]
Looks like [SMART Health IT Sandbox](https://sandbox.smarthealthit.org/) has been changed.  And the tutorial needs to be updated. I am not able to run the application against SMART Health IT Sandbox.

**Comment by kolkheang** [comment]
Hello @cheriannet,

We have a ticket logged to update the tutorial.  We haven't gotten to updating it yet.  In the mean time you can follow this instruction to run your app against SMART Health IT Sandbox site.

- Go to https://dev.smarthealthit.org/
- Scroll down and find 'SMART Launcher' and click on the 'Website' to launch 'SMART App Launcher' in new tab.
- In the App Launch Options select Launch Type as 'Provider EHR Launch' with 'Simulate launch within the EHR user interface' box checked. This is the default.
- Leave the FHIR Version to the default one 'R2(DSTU2)'
- In the 'Patient(s)' section click the drop-down button to open a list of patients in a Pop-up box. Check any patient and click 'Ok'. This should populate the patientID in that field.
- Next in the 'Provider(s)' section click the drop-down button to open a list of providers. Check any Provider to populate the ProviderID in that field.
- For the purpose of this tutorial we will leave the 'Advanced' options as is.
- Update client ID in launch-smart-sandbox.html
`<script>
FHIR.oauth2.authorize( { 'client_id': 'YOUR-SMART-HEALTH-IT-CLIENT-ID-HERE', 'scope': 'patient/Patient.read patient/Observation.read launch online_access openid profile' }
);
</script>`
- Copy this ID and paste it in your `launch-smart-sandbox.html` client ID section (just as you did when you received your Cerner Sandbox client ID). Commit this change in gh-pages branch.
- In your `launch-smart-sandbox.html`, copy the scopes for your application.
- Now back in the SMART Health IT DevBox, scroll down to the field which says 'App Launch URL(required)'. 
- Use the following value but replace <gh-username> with your GitHub username:
https://**<gh-username>**.github.io/smart-on-fhir-tutorial/example-smart-app/launch-smart-sandbox.html
- Now launch the app by clicking on the green 'Launch App' button to see your app opened in the simulated EHR with the patient data.

**Comment by cheriannet** [comment]
Thank you! It worked.  

I am trying to develop an application for a healthcare provider, who wants to display all the current patients in the facility, with their room number, name, age, diagnosis, labs, procedures, treatments etc on the screen. Any tutorials related to that? I need to develop a provider stand-alone application.

**Comment by kolkheang** [comment]
@cheriannet  - No, we don't have a tutorial with sample app with all of these things.  You're welcome to take a look at our FHIR APIs at http://fhir.cerner.com/millennium/dstu2/ to see if you can use the FHIR APIs to get these things.

If you have any further question, feel free to post in our Google Group @ https://groups.google.com/forum/#!forum/cerner-fhir-developers.

**Comment by cheriannet** [comment]
Why was this reopened? Should I close it?

**Comment by kolkheang** [comment]
@cheriannet - I'll issue a PR and link this issue to it.  Then I'll close this issue.

**Comment by kpshek** [comment]
Thanks for logging this @cheriannet - we've updated the tutorial in #50 based upon the latest SMART Health IT Launcher. Thanks for logging this!

**Comment by rizwan1-mansuri** [comment]
Thank you
