### ISSUE TITLE
Cannot read property 'substr' of undefined     at stripTrailingSlash

### ISSUE THREAD

**Issue by kumarsachin031** [cerner/smart-on-fhir-tutorial#53]
Hello, I am added this project in the localhost with this url "http://localhost/launch.html". I am getting this issue "Cannot read property 'substr' of undefined     at stripTrailingSlash".please tell me what i am doing wrong

**Comment by kpshek** [comment]
@kumarsachin031 - Have you tried looking in your browser's Javascript console to debug the issue? That should direct to where the problem bit of code or error is.

**Comment by kumarsachin031** [comment]
Hello,I checked that and found that I am getting str blank in that function.I created the client ip and passed in your example and also  add the url in the app.But still i am getting this error

**Comment by kolkheang** [comment]
@kumarsachin031 - The issue that you're seeing is from this function https://github.com/smart-on-fhir/client-js/blob/9a979e0607f1ed574c5af8979e63e7593a4310a6/src/client/bb-client.js#L34-L39.  

The tutorial is not meant to be launched like that.  If you're working on a standalone SMART application, you'd need to specify the `iss` param in the query parameter to indicate the FHIR server.  Please see this section of the tutorial to find out how to launch it.

http://engineering.cerner.com/smart-on-fhir-tutorial/#standalone-app-launch-for-patient-access-workflow

If you're working on a provider EHR launch, then you'd need to launch the app via [code Console](https://code.cerner.com/developer/smart-on-fhir/).

**Comment by kumarsachin031** [comment]
What value i will put in this  iss param
