### ISSUE TITLE
Problem registering App on Code Cerner

### ISSUE THREAD

**Issue by msdiniz** [cerner/smart-on-fhir-tutorial#72]
After getting Batman at Health page, I'm facing this msg:
![image](https://user-images.githubusercontent.com/7937685/58440435-6d6d7480-80b0-11e9-8b34-59c77a1d8bf0.png)
while trying to register the App, at the second step of the tutorial; I tried in three different systems, with Chrome, IExplorer and Edge, to no avail.

Any directions?

**Comment by kolkheang** [comment]
Thanks for reporting this @msdiniz!  Our system has an issue with locales setting other than `en-US` and `en-GB` at the moment.  This includes registration and testing of your app.  We'll look into this issue further, and prioritize the fix.

As a workaround (non-ideal), you can switch the browser's locale to either `en-US` or `en-GB`.

**Comment by kolkheang** [comment]
@msdiniz 

We have corrected this issue.  Let us know if you are still having problem with app registration.
