### ISSUE TITLE
Cannot find Authorization server

### ISSUE THREAD

**Issue by WebPro9369** [cerner/smart-on-fhir-tutorial#8]
Hi, everyone!
I have some troubles in process of authorization of my SMART App.
In the tutorial, they wrote about Authrization:
"The responsibility of launch.html is to redirect to the appropriate FHIR authorization server. As you can see in the code, fhir-client makes our job pretty easy. All we have to do is call FHIR.oauth2.authorize and supply the client_id generated by the code console during registration and the scopes we registered."

But when I deploy and go to 'https://<your-username>.github.io/smart-on-fhir-tutorial/example-smart-app/', the browser says 'Failed to call FHIR Service'.
Also when I go to  'https://<your-username>.github.io/smart-on-fhir-tutorial/example-smart-app/launch.html' where function FHIR.oauth2.authorize is in, there is an error that is caused by no authorization server is identified.

Of course, I registered my app and now have a Client_ID, and use it in function FHIR.oauth2.authorize, as tutorial says.
I think when go to url 'https://<your-username>.github.io/smart-on-fhir-tutorial/example-smart-app/launch.html', I should give it params 'iss' and 'launch'.
But for this, I need to know url of Authorization server.
It is what I cannot solve, and as it is the beginning of SMART app development, I could make no step in advance.

As I am not familiar with SMART app(though very experienced in api development using JS), really hope to see your kind reply.

Thank you.

**Comment by kolkheang** [comment]
Hi,
Please launch the app via the Code Console site using the Begin Testing button. It will have the value of the iss populated for you.

**Comment by kanhakumar** [comment]
> Hi,
> Please launch the app via the Code Console site using the Begin Testing button. It will have the value of the iss populated for you.

I have done this, but facing the same issue that WebPros9369 was facing. What should I do?
