### ISSUE TITLE
Cannot find Authorization Server

### ISSUE THREAD

**Issue by WebPro9369** [cerner/smart-on-fhir-tutorial#9]
Hi, everyone!
I have some troubles in process of authorization of my SMART App.
In the tutorial, they wrote about Authrization:
"The responsibility of launch.html is to redirect to the appropriate FHIR authorization server. As you can see in the code, fhir-client makes our job pretty easy. All we have to do is call FHIR.oauth2.authorize and supply the client_id generated by the code console during registration and the scopes we registered."

But when I deploy and go to 'https://.github.io/smart-on-fhir-tutorial/example-smart-app/', the browser says 'Failed to call FHIR Service'.
Also when I go to 'https://.github.io/smart-on-fhir-tutorial/example-smart-app/launch.html' where function FHIR.oauth2.authorize is in, there is an error that is caused by no authorization server is identified.

Of course, I registered my app and now have a Client_ID, and use it in function FHIR.oauth2.authorize, as tutorial says.
I think when go to url 'https://.github.io/smart-on-fhir-tutorial/example-smart-app/launch.html', I should give it params 'iss' and 'launch'.
But for this, I need to know url of Authorization server.
It is what I cannot solve, and as it is the beginning of SMART app development, I could make no step in advance.

As I am not familiar with SMART app(though very experienced in api development using JS), really hope to see your kind reply.

Thank you.

**Comment by WebPro9369** [comment]
And what does 'launch' parameter mean and how could I use it?
Thank you.

**Comment by kpshek** [comment]
@WebPro9369 - The `launch` parameter is ultimately how context is shared securely between the EHR and the SMART app. You can read more about SMART app launches, context, and FHIR permissions (scopes) over on [the SMART project homepage](http://docs.smarthealthit.org/authorization/scopes-and-launch-context/).

Regarding your other questions, are you launching your SMART app from [Cerner's Code Console](code.cerner.com/developer/smart-on-fhir)? Assuming you've registered your app there, you should be able to click on the "Begin Testing" button, select a patient for testing, and then click on the "Launch" button to call your SMART app's launch URL.

**Comment by WebPro9369** [comment]
Thank you for your kind reply.
What I need to do is to add a call against an endpoint MedicationStatement(Post & Get).
To do this, I should insert codes of calling api endpoint in somewhere(I think it would be example-smart-app.js).
I tried to use Postman to simulate a process of POST, but failed because it needed OAuth2.0 Authorization.
But GET was succeessful, I think this is because I was working on Sandbox.
So could you please let me know if POST is possible on Sandbox?
It seems that Sandbox does not allow Authorization, it is just a place to demo try.
Waiting for your reply.
Thank you

**Comment by kpshek** [comment]
Cerner's FHIR Sandbox does allow for write transactions (POST requests). However, in order to perform a POST request you must have a valid OAuth 2 access token (Bearer token).

**Comment by MayankTiwari1011** [comment]
> Hi, everyone!
> I have some troubles in process of authorization of my SMART App.
> In the tutorial, they wrote about Authrization:
> "The responsibility of launch.html is to redirect to the appropriate FHIR authorization server. As you can see in the code, fhir-client makes our job pretty easy. All we have to do is call FHIR.oauth2.authorize and supply the client_id generated by the code console during registration and the scopes we registered."
> 
> But when I deploy and go to 'https://.github.io/smart-on-fhir-tutorial/example-smart-app/', the browser says 'Failed to call FHIR Service'.
> Also when I go to 'https://.github.io/smart-on-fhir-tutorial/example-smart-app/launch.html' where function FHIR.oauth2.authorize is in, there is an error that is caused by no authorization server is identified.
> 
> Of course, I registered my app and now have a Client_ID, and use it in function FHIR.oauth2.authorize, as tutorial says.
> I think when go to url 'https://.github.io/smart-on-fhir-tutorial/example-smart-app/launch.html', I should give it params 'iss' and 'launch'.
> But for this, I need to know url of Authorization server.
> It is what I cannot solve, and as it is the beginning of SMART app development, I could make no step in advance.
> 
> As I am not familiar with SMART app(though very experienced in api development using JS), really hope to see your kind reply.
> i am trying to launch app getting error like .Information to provide to Unknown Application
The supplied "client_id" value does not correspond to any registered applications on record..kindly solve my problem
![clientid error

> Thank you.

**Comment by MayankTiwari1011** [comment]
i am trying to launch app getting error like .Information to provide to Unknown Application
The supplied "client_id" value does not correspond to any registered applications on record..kindly solve my problem
![clientid error

Thank you.
