### ISSUE TITLE
Update client id in launch.html to be clearer that it must be changed

### ISSUE THREAD

**Issue by MaxPhilips** [cerner/smart-on-fhir-tutorial#96]
In the [launch.html](https://github.com/cerner/smart-on-fhir-tutorial/blob/10fd6cc26ba1089f018089310b17c7a385969ef0/example-smart-app/launch.html#L29) file we currently have a bogus client id. It might be clearer to users of the tutorial that the client id must be replaced in order to launch their app if the value for the client id was something like
```
<client id>
```

In the tutorial site, we do use a throwaway value for the client id in the code example https://engineering.cerner.com/smart-on-fhir-tutorial/#request-authorization

**Comment by xiaoningmzhang** [comment]
Addressed in PR #105.
